### ISSUE TITLE
exit event should include step user exited at.

### ISSUE THREAD

**Issue by Dandada1993** [fatihsolhan/v-onboarding#107]
Hi, I am trying to ascertain if there is a way to determine what step the user exited on. That way I can restart the on-boarding on the next step. Is it possible for the exit event to return the step?

**Comment by fatihsolhan** [comment]
Hi @Dandada1993 ! 👋

I've implemented your feature request to include the current step index in the exit event. The change has been merged and will be available in the next release.

Now you can access the step index where the user exited like this:
```typescript
const onExit = (stepIndex: number) => {
  console.log(`User exited at step ${stepIndex}`);
}
```
Since you have access to the `steps` where you handle this event, you can get the step data using the index like `steps.value[stepIndex]`

Thanks for the suggestion! Let me know if you need anything else. 🙌
