### ISSUE TITLE
Can this be used for Vue 2?

### ISSUE THREAD

**Issue by kathirr007** [fatihsolhan/v-onboarding#30]
Can this be used for Vue 2?

**Comment by fatihsolhan** [comment]
Hi @kathirr007 

v-onboarding is not compatible with Vue2 right now but Vue2 support is in my todo list.
I am planning to release Vue2 compatible version on next weekend

**Comment by kathirr007** [comment]
Hi Fatih Solhan,

Thank you, waiting for the release of the Vue2 compatible version.

**Comment by fatihsolhan** [comment]
Hey @kathirr007 

I planned to use [`vue-demi`](https://github.com/vueuse/vue-demi) for the Vue2 compatibility. I've been working on it for 2 days but unfortunately, `vue-demi` didn't work for us.
As @LinusBorg explained here https://github.com/vuejs/rollup-plugin-vue/issues/427#issuecomment-753867261 I don't think `vue-demi` will work for `v-onboarding`

I will probably need to create a Vue2 compatible version from scratch and release it under a different name but I cannot estimate how long it will take due to my current workload.

Sorry that I couldn't help you.
I appreciate your interest in `v-onboarding` ❤️

**Comment by kathirr007** [comment]
Hi Fatih,

No worries, thanks for the update!. It would be helpful if we get a Vue2
compatible version soon.
I'll always look for the update.

Thank you,
Kathiravan K.

**Comment by Sanan4li** [comment]
I think it's still not available for vue 2. Any suggestions to use other package for a lagacy project developed with vue 2?
