### ISSUE TITLE
Tried changing button titles - nothing happened

### ISSUE THREAD

**Issue by DominikGanic** [fatihsolhan/v-onboarding#51]
Hi, I don't know if it's my bad now or not, but I've tried changing the button titles as in the documentation using the labels object. 

Here's my code snippet which should change the button title for this step:

![image](https://user-images.githubusercontent.com/13388387/200547734-f9c47a50-1c5b-4fde-8e91-4a3bca399105.png)

The button title for the next button with value "Irgendwas" doesn't apply - did I do something wrong?

Another misunderstood case is the overriding of the OnboardingWrapper. Where should I pass the options to change the button titles globally? The documentation is somehow lacking here with samples. :(

Another idea: Could you let us integrate images / assets into the steps? So we could also show some illustrations with the steps. That would be great!

Thanks for your effort again - this plugin has still huge potential as other alternatives are really bad tho and this one works really cool so far. :)

**Comment by DominikGanic** [comment]
Hi @fatihsolhan, great, thanks for your **very fast response**!

I've researched myself the source code and came up with the global wrapper options solution - **and it works great**! So in this case, it was my fault and I'm sorry for opening a bug issue way too early. :) Everythin works great.

**Comment by fatihsolhan** [comment]
Hey @DominikGanic, no worries. I'm glad you resolved the global options question.

You can pass the `options` prop to the `VOnboardingWrapper` component. Options are listed [on this page](https://v-onboarding-docs.fatihsolhan.com/props/options)

For the images/assets part; I believe it makes more sense to make those customizations with the custom UI. Because if we somehow allow passing an illustration/image to the default UI, the custom UI will be meaningless.
I definitely recommend using a custom UI in your case.

Please let me know if this makes sense to you or if you need help with the custom UI
