### ISSUE TITLE
Restart doesn't work after finish

### ISSUE THREAD

**Issue by or2e** [fatihsolhan/v-onboarding#70]
**Describe the bug**
After finishing/closing onboarding doesn't work restarting onboarding

**To Reproduce**
1. start onboaring
2. go to the last step and press finish onboaring || just close onboarding at any step
3. сlick on start again
4. onboarding Poppers doesn't open

Here is the [link ](https://stackblitz.com/edit/vitejs-vite-ev5rjh?file=src/App.vue) where the problem is reproduced.
Or in the library demo https://v-onboarding.fatihsolhan.com/

<details>
<summary>Also, there is a Warning in the console</summary>

![image](https://user-images.githubusercontent.com/33551334/236951672-212aa5de-93fa-45e7-8bc8-a6d37ea75331.png)
</details>

ty!

**Comment by rozsazoltan** [comment]
This is not actually an error, but an expected behavior, although the operation is not clear. When you `finish` the last step, we consider the process to be over, so we **remove the component from the DOM** (`v-if="!isFinished"`), and it cannot be called again with the `start()` function.

I have made a modification that makes it available as an option in the `options` not to consider the `finish` so strictly, allowing you to review the steps even after the completion. I will soon publish it in a pull request.

**Comment by fatihsolhan** [comment]
Hey @or2e and @rozsazoltan,

Kudos to you, @or2e, for spotting the onboarding restart issue. I appreciate it ❤️ 

@rozsazoltan, your investigation was much appreciated ❤️ . It turns out there was a more straightforward solution to the issue. When onboarding gets restarted, v-onboarding wasn't able to find the correct element right away. We've now added a nextTick to delay it to the next tick, which helped us solve the problem neatly.

We've got this sorted out in version 2.5.1. You both rock!
