### ISSUE TITLE
Slide Hooks: Before & After

### ISSUE THREAD

**Issue by shealavington** [fatihsolhan/v-onboarding#74]
**The Problem:**
I have a page with records in a table, this page has a button which opens a modal, the modal allows you to create a new record. I would like my users to know how to create the records.

**Thoughts on a solution**
Could we somehow introduce "before" and "after" hooks for each "slide", just functions that run before and after each slide is loaded on the Dom.

Slide one says "this opens the modal"
Slide 2 Before: perform "modal.open()"
(modal opens)
Slide 2 says "Enter the record name"
Slide 3 says click Submit
(I don't actually want to submit anything)
Slide 3 After: "modal.close()"
Slide 4 Results are shown in this table

Not entirely sure how this works in reverse as I write it, maybe it needs to be on the next/previous beforeNext beforePrevious?

Then when going in reverse I could say beforePrevious and perform the modal.open() again. 

**Additional context**
I completely understand if this over complicates the library, but would be interesting to hear additional thoughts from others. 🙂

I just think it adds a bit more flexibility for things like interactive systems.

_If I get the chance, I'll have a think of a solution and send a PR, but sounds like y'all have a good grasp on the library and where to take it._ 🚀

**Comment by rozsazoltan** [comment]
Hi!

## Avaliable

Do the `beforeStep()` and  `afterStep()` functions not serve the purpose?
[Docs](https://v-onboarding-docs.fatihsolhan.com/props/steps)

**beforeStep**: Executes anything you pass to it before displaying the step.

**afterStep**: Executes anything you pass to it after displaying the step.

You can configure this on a step-by-step basis.

## Review

Essentially, if you click the "next" button, then the `beforeStep` of the next step would correspond to your `beforeNext` logic.

If I want to integrate it into the current code, the `beforePrevious` should be inserted into the `beforeStep` of the previous element to check if the modal is open and close it.

## Solution

I think the `beforeNext` is straightforward; it corresponds to the `beforeStep` of the next element. The `beforePrevious` is more thought-provoking. It would save a few conditionals, but instead of creating a new function, I would pass an argument to the `beforeStep` and `afterStep` functions indicating whether the current step is a "backward" or "forward" step in the sequence. Using this, you can reference it within the function.

#### Now
```js
const step = {
  on: {
    beforeStep: () => { /* ... */ },
    afterStep: () => { /* ... */ }
  }
}
```

#### Feature
```js
const step = {
  on: {
    beforeStep: (type?: "forward" | "backward") => { /* ... */ },
    afterStep: (type?: "forward" | "backward") => { /* ... */ }
  }
}
```

The original argument-less function definition, `() => { ... }`, will continue to work. However, if you need to differentiate the logic based on whether it's a forward or backward step, you have the option to do so.

```js
const step = {
  on: {
    beforeStep: (type) => { 
      if (type === "backward") {
        // For example, if the next step would open in a modal, it would be helpful to close it when going backward.
        modal.close(); 
      }
    },
  }
}
```

**Comment by shealavington** [comment]
You are totally right! I couldn't find them in the documentation, upon re-checking, I did find them tucked away on the steps page, thanks for pointing that one out. 

Much appreciated—and sorry for wasting your time having to point it out to me. :)
